function sigDEN = my_denoise_func(SIG)
% FUNC_DENOISE_DW1D Saved Denoising Process.
%   SIG: vector of data
%   -------------------
%   sigDEN: vector of denoised data

%  Auto-generated by Wavelet Toolbox on 07-Dec-2019 17:54:30

% Analysis parameters.
%---------------------
wname = 'db3';
level = 7;

% Denoising parameters.
%----------------------
% meth = 'sqtwolog';
% scal_or_alfa = sln;
sorh = 'h';    % Specified soft or hard thresholding
thrSettings = 0.592229294553382;

% Denoise using CMDDENOISE.
%--------------------------
sigDEN = cmddenoise(SIG,wname,level,sorh,NaN,thrSettings);
